#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2026, Tuxthepirate (@Doubleth1nk)
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

from __future__ import annotations

DOCUMENTATION = r'''
---
module: user
short_description: Manage Artifact Keeper users
version_added: "0.2.0"
description:
  - Creates, updates, and deletes Artifact Keeper users.
  - The user is identified by its exact O(username). An email address never matches O(username).
  - Service accounts are managed by M(artifactkeeper.core.service_account), not by this module.
  - Omitted optional fields are left unmanaged.
  - Changing or resetting the password of an existing user is intentionally outside the scope of this module.
author:
  - Tuxthepirate (@Doubleth1nk)
extends_documentation_fragment:
  - artifactkeeper.core.artifactkeeper
options:
  username:
    description:
      - Exact username. This is the stable identity of the user and cannot be changed.
    type: str
    required: true
  email:
    description:
      - Email address. Required when the user does not exist yet.
      - Compared exactly as returned by Artifact Keeper.
    type: str
  display_name:
    description:
      - Display name. Managed when supplied.
      - The API cannot clear a display name once it is set.
    type: str
  is_admin:
    description: Whether the user is an administrator. Managed when supplied.
    type: bool
  is_active:
    description: Whether the user is active. Managed when supplied.
    type: bool
  password:
    description:
      - Initial password, only used when the user is created.
      - When omitted on creation, Artifact Keeper may generate a password, which is returned once as RV(generated_password).
      - For an existing user the password is not sent, compared, or changed, and the module emits a warning.
    type: str
  state:
    description: Whether the user should exist.
    type: str
    choices: [present, absent]
    default: present
notes:
  - "Use task-level C(no_log: true) when a task can create a user, because the result can contain RV(generated_password)."
'''

EXAMPLES = r'''
- name: Create a user with an initial password
  artifactkeeper.core.user:
    api_url: https://artifacts.example.com
    token: "{{ artifactkeeper_token }}"
    username: alice
    email: alice@example.com
    display_name: Alice
    password: "{{ alice_initial_password }}"
  no_log: true

- name: Create a user and let Artifact Keeper generate a password
  artifactkeeper.core.user:
    api_url: https://artifacts.example.com
    token: "{{ artifactkeeper_token }}"
    username: bob
    email: bob@example.com
  register: bob_user
  no_log: true

- name: Deactivate a user
  artifactkeeper.core.user:
    api_url: https://artifacts.example.com
    token: "{{ artifactkeeper_token }}"
    username: carol
    is_active: false

- name: Delete a user
  artifactkeeper.core.user:
    api_url: https://artifacts.example.com
    token: "{{ artifactkeeper_token }}"
    username: dave
    state: absent
'''

RETURN = r'''
user:
  description:
    - User after the change, or C(null) when the user is absent.
    - In check mode this is the predicted user.
  returned: always
  type: dict
  contains:
    id:
      description: Artifact Keeper user UUID.
      type: str
      returned: when the user exists on the server
    username:
      description: Username.
      type: str
      returned: always
    email:
      description: Email address.
      type: str
      returned: always
    display_name:
      description: Display name.
      type: str
      returned: when set
    is_active:
      description: Whether the account is active.
      type: bool
      returned: always
    is_admin:
      description: Whether the account is an administrator.
      type: bool
      returned: always
changed_fields:
  description: Managed fields that differed from the server state. Never contains the password.
  returned: always
  type: list
  elements: str
generated_password:
  description:
    - Password generated by Artifact Keeper because none was supplied. This is sensitive.
  returned: only when Artifact Keeper creates the user and generates a password
  type: str
'''

from ansible_collections.artifactkeeper.core.plugins.module_utils.common import (
    client_from_module,
    fail_from_exception,
    make_module,
    managed_diff,
    q,
    safe_diff,
    user_by_username,
    users_by_username,
)

MANAGED_FIELDS = ("email", "display_name", "is_admin", "is_active")


def _desired(p):
    return {field: p[field] for field in MANAGED_FIELDS if p.get(field) is not None}


def _create(module, client, p):
    username = p["username"]
    if any(row.get("is_service_account") for row in users_by_username(client, username)):
        module.fail_json(
            msg="username '%s' belongs to a service account; manage it with artifactkeeper.core.service_account" % username
        )
    if p.get("email") is None:
        module.fail_json(msg="email is required to create user '%s'" % username)

    desired = _desired(p)
    payload = {"username": username, "email": p["email"]}
    for field in ("display_name", "is_admin"):
        if field in desired:
            payload[field] = desired[field]
    if p.get("password") is not None:
        payload["password"] = p["password"]

    preview = {
        "username": username,
        "email": p["email"],
        "display_name": p.get("display_name"),
        "is_admin": desired.get("is_admin", False),
        "is_active": desired.get("is_active", True),
        "is_service_account": False,
    }
    result = {"changed": True, "user": preview, "changed_fields": sorted(desired)}
    if getattr(module, "_diff", False):
        result["diff"] = safe_diff({}, preview, secrets=(p.get("password"),))
    if module.check_mode:
        module.exit_json(**result)

    response = client.post("/users", data=payload, expected=(200,))
    user = response.get("user")
    if desired.get("is_active") is False:
        user = client.patch("/users/%s" % q(user["id"]), data={"is_active": False}, expected=(200,))
    result["user"] = user
    if response.get("generated_password"):
        result["generated_password"] = response["generated_password"]
    module.exit_json(**result)


def run_module(module, client):
    p = module.params
    existing = user_by_username(client, p["username"])

    if p["state"] == "absent":
        if not existing:
            module.exit_json(changed=False, user=None, changed_fields=[])
        result = {"changed": True, "user": existing, "changed_fields": ["user"]}
        if getattr(module, "_diff", False):
            result["diff"] = {"before": existing, "after": {}}
        if module.check_mode:
            module.exit_json(**result)
        client.delete("/users/%s" % q(existing["id"]), expected=(200,))
        result["user"] = None
        module.exit_json(**result)

    if not existing:
        _create(module, client, p)

    if p.get("password") is not None:
        module.warn(
            "password is only used when creating a user; the existing password of user '%s' was not changed. "
            "Password change/reset is not managed by this module." % p["username"]
        )

    desired = _desired(p)
    changed_fields, before, after = managed_diff(existing, desired, desired.keys())
    if not changed_fields:
        module.exit_json(changed=False, user=existing, changed_fields=[])

    changes = {field: desired[field] for field in changed_fields}
    result = {"changed": True, "user": {**existing, **changes}, "changed_fields": changed_fields}
    if getattr(module, "_diff", False):
        result["diff"] = safe_diff(
            {field: before[field] for field in changed_fields},
            {field: after[field] for field in changed_fields},
            secrets=(p.get("password"),),
        )
    if module.check_mode:
        module.exit_json(**result)

    result["user"] = client.patch("/users/%s" % q(existing["id"]), data=changes, expected=(200,))
    module.exit_json(**result)


def main():
    module = make_module(
        {
            "username": {"type": "str", "required": True, "no_log": False},
            "email": {"type": "str"},
            "display_name": {"type": "str"},
            "is_admin": {"type": "bool"},
            "is_active": {"type": "bool"},
            "password": {"type": "str", "no_log": True},
            "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
        }
    )
    try:
        run_module(module, client_from_module(module))
    except Exception as exc:
        fail_from_exception(module, exc)


if __name__ == "__main__":
    main()
